### ISSUE TITLE
Could not open input file : artisan

### ISSUE THREAD

**Issue by junedc** [creativetimofficial/vue-argon-dashboard-laravel#2]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ YES] I am running the latest version
- [ YES] I checked the documentation and found no answer
- [ YES] I checked to make sure that this issue has not already been filed
- [ YES] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

composer install must install needed package and return to the terminal prompt

# Current Behavior

its throwing an error
Could not open input file: artisan
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

just download the laravel-json-api-pro packages and run composer install

## Context

* Device:   mcbook 
* Operating System:   catalina

* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

<img width="1066" alt="Screen Shot 2021-04-07 at 3 13 42 PM" src="https://user-images.githubusercontent.com/14034808/113805349-7b17d900-97b4-11eb-9cec-36599b2c82b4.png">

**Comment by teamupdivision** [comment]
Hi @junedc,

Thank you for reporting this issue and for using Creative Tim products.
 
Could you please send a few more details to us? Also, if you can send to us a video recording with the steps, it will help a lot in investigating this further.
 
All the best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi there @junedc,

We would like to check if the issue was solved or if you can share a few more details on the steps followed. Please let us know if there is anything else we can help with and if you have any other issues.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi there @junedc, 

We were curious if the issue was solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

**Comment by junedc** [comment]
heres the video link https://www.youtube.com/watch?v=YqMCn8bCto8 for the error

**Comment by teamupdivision** [comment]
Hi @junedc,

Thank you for sharing the recording. This helped a lot in understanding the issue. We've pushed a fix to this problem.
Please download again the product from the downloads section on the Creative Tim website.

Let us know if everything works well now and if there is anything else we can help with. 

All the best,
UPDIVISION Team

**Comment by junedc** [comment]
ok thanks for the update.  I'll check in my download area.

P.S.
I'm not sure thought why you share the github address.  it says 404 on my end

**Comment by teamupdivision** [comment]
Hi @junedc,

Thank you. The GitHub address was sent by mistake. Sorry for the confusion. We'll update the comment above to avoid any misunderstandings. 

Please let us know if you have any other issues.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi there @junedc, 

We would like to check if the issue was solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @junedc,
 
Hope this solved the problem. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
